#!/bin/bash
set -e

echo "Installing automatic updates..."

if crontab -l | grep -q "sudo apt -y update"; 
then 
  echo "Auto update of package list already exists in crontab"
else
  echo "Adding auto update of package list to crontab"
  (crontab -l || true; echo "0 3 * * * sudo apt -y update") | crontab - 
fi

if crontab -l | grep -q "sudo apt -y dist-upgrade"; 
then 
  echo "Upgrade of installed packages already exists in crontab"
else
  echo "Adding upgrade of installed packages"
  (crontab -l || true; echo "0 4 * * * sudo apt -y upgrade") | crontab - 
fi

echo "Installation complete. Enjoy!"

